import { Geist, Geist_Mono } from 'next/font/google';
import Header from './components/Header';
import tw from 'tailwind-styled-components';
import './globals.css';

export const metadata = {
  title: "Jasper Bucad's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className='  bg-[#E5E5E5]
  [background-size:35px_35px]
  [background-image:linear-gradient(to_right,_black_1px,_transparent_1px),linear-gradient(to_bottom,_black_1px,_transparent_1px)]
  '
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
