import { Geist, Geist_Mono } from "next/font/google";
import Header from './components/Header';
import './globals.css';

export const metadata = {
  title: "Jasper Bucad's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
